### ISSUE TITLE
Kicad V8, "index out of range

### ISSUE THREAD

**Issue by groundstack** [bennymeg/Fabrication-Toolkit#153]
![2024-04-11-114416](https://github.com/bennymeg/Fabrication-Toolkit/assets/1927813/1988aac8-925f-4607-b02f-917d37259a22)

I get this error when I launch Fabrication Toolkit and after the options dialog.
Any direction where to look?
I use Kicad V8.0.1 release build. python 3.12.2

**Comment by Duckle29** [comment]
See https://github.com/bennymeg/Fabrication-Toolkit/issues/133#issuecomment-1984158997

**Comment by bennymeg** [comment]
Fixed
