### ISSUE TITLE
Compatibility on Mac 14.4.1, KiCad 8.0.1 & Fabrication Toolkit V4.3.0

### ISSUE THREAD

**Issue by FrankNz** [bennymeg/Fabrication-Toolkit#155]
### Discussed in https://github.com/bennymeg/Fabrication-Toolkit/discussions/154

<div type='discussions-op-text'>

<sup>Originally posted by **FrankNz** April 15, 2024</sup>
Hello, 
The Fab-Toolkit runs on the above combination but does not present the config menus as displayed on Github. The only window that opens is the one below. I have used this S/W before on earlier Mac/KiCad combinations and it worked ok then.
Clicking 'Generate' does generate a set of files. 
Maybe I'm doing something wrong?
<img width="722" alt="Screenshot 2024-04-15 at 10 02 21" src="https://github.com/bennymeg/Fabrication-Toolkit/assets/10928777/05c7720d-1b11-452b-b2b2-ac165461ea66">
</div>

**Comment by bennymeg** [comment]
what other screens? all the other screens in the readme are from the schematic editor.
It seems that you do not have the latest version.

**Comment by FrankNz** [comment]
Thank you for the reply.
You are correct, it seems I need more coffee and to read more carefully. 
I have now updated to the latest release. Thank you
