### ISSUE TITLE
"JLCPCB Rotation Offset" is not working for positions.csv

### ISSUE THREAD

**Issue by digidhamu** [bennymeg/Fabrication-Toolkit#156]
I could see no effect on "JLCPCB Rotation Offset" after generating the positions.csv file.

**Versions Used**
KiCad 8.0.1
Toolkit 4.3.0

**Screenshots**
<img width="587" alt="image" src="https://github.com/bennymeg/Fabrication-Toolkit/assets/9908852/dc6f6c9a-7348-4b52-aaf2-3f6bc4877ad1">

<img width="356" alt="image" src="https://github.com/bennymeg/Fabrication-Toolkit/assets/9908852/ec37b5ef-fa15-480f-adf8-ddb05b8d9b29">

Please advise

**Comment by bennymeg** [comment]
did you synced the schematic before invoking the plugin?

**Comment by digidhamu** [comment]
Yes I did sync.

**Comment by bennymeg** [comment]
Working it the latest release
