### ISSUE TITLE
Automatic Translation

### ISSUE THREAD

**Issue by AndyW999** [bennymeg/Fabrication-Toolkit#157]
KiCad 8.0.1
Toolkit - current

Automatic Translation solves the problems I was having moving from V3 whereby EasyEDA footprints translated to KiCad were rotated wrongly.

But there is still a problem where some parts are offset.

Is there a way around this, and do you want any of the parts to check?

**Comment by bennymeg** [comment]
I am trying to automate the translating matching as much as I can.
The parts that are left should be adjusted manually.

**Comment by AndyW999** [comment]
OK - thanks ;)
