### ISSUE TITLE
[Feature Request]: Add help for initial options

### ISSUE THREAD

**Issue by FrightRisk** [bennymeg/Fabrication-Toolkit#162]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/bennymeg/Fabrication-Toolkit/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

How are these features used? What do they do and when would I want them and when would I not want them? 

![image](https://github.com/bennymeg/Fabrication-Toolkit/assets/37218136/9109ba75-889c-4c2c-8a9c-374c216a0a32)

### Proposed Solution

Would like help added to this github README to explain the options

### Alternatives Considered

.

**Comment by FredM67** [comment]
I cannot find the difference between "Set User.1 as V-Cut Layer" checked or unchecked.
How should a V-Cut line be shown on the JLCPCB side?
