### ISSUE TITLE
[Bug]: "getboundingbox: Expected 2 arguments, got 3"

### ISSUE THREAD

**Issue by Bowlsnapper** [bennymeg/Fabrication-Toolkit#173]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/bennymeg/Fabrication-Toolkit/issues) for a bug report that matches the one I want to file, without success.

### Fabrication Toolkit Version

4.1.1

### What operating system are you using?

Windows

### Operating System Version

Win11

### What arch are you using?

x64

### Expected Behavior

Normal

### Actual Behavior

When creating the files, I get an error stating, "FOOTPRINT_Getboundingbox expected 2 arguments, got 3. Wrong number of arguments."

I am using the latest nightly of kicad, which I should not be doing and I am now stuck with this issue, unfortunately. Other projects work fine in the nightly still, but I did something in this project that your plugin doesn't like. Any ideas?

![image](https://github.com/user-attachments/assets/9324db1f-b0e4-433b-b773-9029bfda3d99)

**Comment by bennymeg** [comment]
you have to many comma's
